#
#  Copyright 2022 Paul Guyot <pguyot@kallisys.net>
#
#  SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later
#

name: Run tests with BEAM

on:
  push:
    paths-ignore:
      - 'src/platforms/esp32/**'
      - 'src/platforms/stm32/**'
      - 'doc/**'
      - 'LICENSES/**'
  pull_request:
    paths-ignore:
      - 'src/platforms/esp32/**'
      - 'src/platforms/stm32/**'
      - 'doc/**'
      - 'LICENSES/**'

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-20.04"]
        otp: ["21", "22", "23"]

        include:
        - os: "ubuntu-20.04"
          test_erlang_opts: "-s prime_smp"

        - os: "macos-latest"
          cmake_opts: "-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl"

        - os: "macos-latest"
          otp: "21"
          path_prefix: "/usr/local/opt/erlang@21/bin:"

        - os: "macos-latest"
          otp: "22"
          path_prefix: "/usr/local/opt/erlang@22/bin:"

        - os: "macos-latest"
          otp: "23"
          path_prefix: "/usr/local/opt/erlang@23/bin:"

    steps:
    # Setup
    - name: "Checkout repo"
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: erlef/setup-beam@v1
      if: runner.os == 'Linux'
      with:
        otp-version: ${{ matrix.otp }}

    - name: "Install deps (Linux)"
      if: runner.os == 'Linux'
      run: |
        sudo apt update -y
        sudo apt install -y cmake gperf zlib1g-dev ninja-build

    - name: "Install deps (macOS)"
      if: runner.os == 'macOS'
      run: brew install gperf erlang@${{ matrix.otp }} ninja

    # Build
    - name: "Build: create build dir"
      run: mkdir build

    - uses: actions/cache@v2
      id: cache
      with:
        path: 'build/tests/**/*.beam'
        key: ${{ matrix.otp }}-${{ hashFiles('**/run-tests-with-beam.yaml', 'tests/**/*.erl') }}

    - name: "Build: run cmake"
      working-directory: build
      run: |
        export PATH="${{ matrix.path_prefix }}$PATH"
        cmake -G Ninja ${{ matrix.cmake_opts }} ..

    - name: "Touch files to benefit from cache"
      working-directory: build
      run: |
        # git clone will use more recent timestamps than cached beam files
        # touch them so we can benefit from the cache and avoid costly beam file rebuild.
        find . -name '*.beam' -exec touch {} \;

    - name: "Build: run ninja"
      working-directory: build
      run: |
        export PATH="${{ matrix.path_prefix }}$PATH"
        ninja

    # Test
    - name: "Test: test-erlang with BEAM"
      timeout-minutes: 10
      working-directory: build
      run: |
        export PATH="${{ matrix.path_prefix }}$PATH"
        ./tests/test-erlang -b ${{ matrix.test_erlang_opts }}

    # Test
    - name: "Test: estdlib/ with BEAM"
      timeout-minutes: 10
      working-directory: build
      run: |
        export PATH="${{ matrix.path_prefix }}$PATH"
        erl -pa tests/libs/estdlib/ -pa tests/libs/estdlib/beams/ -pa libs/etest/src/beams -s tests -s init stop -noshell
